version: "3.3"

networks:
    internal:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
          - "80:80"
          - "85:85"  
        volumes:
          - ./sites:/var/www
          - ./config/nginx:/etc/nginx/conf.d
          - ./data/logs:/var/log/nginx/
        depends_on:
          - php
          - mysql
        networks:
          - internal
     
    php:
       build:
         context: ./config/php
         dockerfile: Dockerfile
       container_name: php
       volumes:
         - ./sites:/var/www
         - ./config/php/php.ini:/usr/local/etc/php/php.ini
       ports:
         - "9000:9000"
       networks:
         - internal
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        command: --innodb_use_native_aio=0
        ports:
          - "3306:3306"
        volumes:
          - ./data/mysql:/var/lib/mysql
        
        environment:
          MYSQL_ROOT_PASSWORD: devpass
        networks:
         - internal
