FROM php:5.6-fpm
# RUN выполняет идущую за ней команду в контексте нашего образа. В данном случае мы установим некоторые зависимости и модули PHP. Для установки модулей используем команду 
# docker-php-ext-install. На каждый RUN создается новый слой в образе, поэтому рекомендуется объединять команды.
RUN apt-get update && apt-get install -y \
        curl \
        wget \
        git \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
		libzip-dev \
    && docker-php-ext-install -j$(nproc) iconv mbstring mysqli pdo_mysql zip mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
    
# Ставим Composer'а.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer USER www-data:www-data
# Указываем рабочую директорию для PHP
WORKDIR /var/www
# Запускаем контейнер
CMD ["php-fpm"]
